---
title: "Publications"
---

## Books

- **[ES] *Lecciones privadas de Stuttgart (Schelling)*.** Barcelona: Herder & Charles University (Cooperatio), 2024. *ISBN: 9788425451584*
- **[FR] *L’abîme de l’imagination. L’essor et la chute de l’idéalisme esthétique chez Kant et Schelling*.** Libri virides, 2022. *ISBN: 9783959485678*
- **[ES] *Schelling y el vórtice de lo real. Libertad e individualidad en el escrito sobre la libertad humana de 1809*.** Teseo Press & Charles University (Cooperatio), 2022. *ISBN: 9789878853932*

## Articles (selected 2022-2025)

- **Die Genese der strengen Endlichkeit in Schellings *Philosophie und Religion***.  
  *Deutsche Zeitschrift für Philosophie*, **73**(2), 194–217.  
  DOI: <https://doi.org/10.1515/dzph-2025-0013>

- **The Unity of Love and the ‘External Unity’, or Schelling’s Anarchist Critique of the State in the Stuttgart Lectures**.  
  *International Journal of Philosophical Studies*, online first (21 May 2025).  
  DOI: <https://doi.org/10.1080/09672559.2025.2498988>

- **Against Constructivism. Schelling’s Critique of the Idealist Concept of System in the Stuttgart Private Lectures**.  
  *History of Philosophy Quarterly*, **42**(1), 67–89.  
  DOI: <https://doi.org/10.5406/21521026.42.1.4>

- **Freedom as a Detachment of Finite Beings from the Absolute in Schelling’s *Bruno***.  
  *Philosophical Inquiries*, **12**(2), 55–77.  
  DOI: <https://doi.org/10.4454/philinq.v12i2.507>

- **Schelling’s Ontological Turn: Pronominal Being against Fichte’s Idealism of Absolute Reflection**.  
  *Sophia*, **64**(1), 21–35 (7 Feb 2025).  
  DOI: <https://doi.org/10.1007/s11841-024-01058-2>

- **Hegel’s Vanity.**  
  _International Journal of Philosophy and Theology_, **84**(1), 1–17 (2023).  
  DOI: <https://doi.org/10.1080/21692327.2023.2188243>

- **A Dark Nature. Schelling on the world and freedom in the years 1806–1810.**  
  _Idealistic Studies_, **52**(2), 179–199 (2022).  
  DOI: <https://doi.org/10.5840/idstudies202255141>