
---
title: "Talks & Conferences"
---

## 2024

- **03 Dec 2024 — Prague**  
  *Le rôle de l'objet intentionnel dans l’origine de la phénoménologie à la lumière du débat sur le réalisme dans la philosophie contemporaine.*  
  **Critical Perspectives on Phenomenology: Investigations of the world, environment, nature**, Charles University / Czech Academy of Sciences. *Invited.*

- **23 May 2024 — Spokane (USA)**  
  *The Unity of Love and the ‘External Unity’.*  
  **Controversial Schelling**, Eighth Meeting of the North American Schelling Society (NASS), Gonzaga University. *Invited.*
- **16 Apr 2024 — Wuppertal**  
  *Schelling über Freiheit, Anarchismus und Liebe und seine Bedeutung für eine politische Theorie der neuzeitlichen.*  
  **Forschungsseminar (Prof. A. Schnell)**, Bergische Universität Wuppertal.

- **13 Mar 2024 — Nice**  
  *Conséquences éthiques de la conception pré-objective du mouvement chez Patočka.*  
  **L'actualité de la phénoménologie**, Université Côte d’Azur. *Invited.* 


## 2020–2023 (selected)

- **11 Nov 2023 — Prague**  
  *Annäherung an die Wahrnehmung in leiblicher Hinsicht in Husserl und Merleau-Ponty.*  
  **Critical Perspectives of Phenomenology. Wahrnehmung, Imagination, Fiktion**, Charles University, Faculty of Humanities. *Invited.* 

- **06 Jun 2023 — Wuppertal**  
  *Schellings Lehre des Bandes.* **Forschungsseminar (Prof. A. Schnell)**, Bergische Universität Wuppertal. 

- **25 Oct 2022 — Wuppertal**  
  *Die Trennung zwischen dem Absoluten und der Welt in Schellings *Bruno* sowie in *Philosophie und Religion*.*  
  **Forschungsseminar (Prof. A. Schnell)**, Bergische Universität Wuppertal. 

- **10 Jun 2022 — Erfurt**  
  *Schelling und Heidegger über Dasein und Freiheit.*  
  **VI Internationale Meßkircher Heidegger-Konferenz** “Heidegger & Schelling / Schelling & Heidegger”, Universität Erfurt. *Invited.* 

- **15 Dec 2020 — Wuppertal**  
  *Die innerliche Unmöglichkeit eines Systems der Freiheit bei Schelling.*  
  **Forschungsseminar (Prof. A. Schnell)**, Bergische Universität Wuppertal. 
